create procedure FI_SP_IncBeneficiarioV1  
 @CPF VARCHAR(11),  
 @NOME VARCHAR(50),  
 @IDCLIENTE BIGINT  
AS  
BEGIN  
 INSERT INTO BENEFICIARIOS (CPF , NOME , IDCLIENTE)  
 VALUES (@CPF, @NOME,@IDCLIENTE)  
  
 SELECT SCOPE_IDENTITY()  
END